apiVersion: v1
kind: Service
metadata:
  name: helloworld-service-nodeport
spec:
  ports:
  - port: 8888
    nodePort: 36000
    targetPort: nginxport
    protocol: TCP
  selector:
    app: helloworld
  type: NodePort
